### PR TITLE
mgos_i2c_setbits_reg_w endianness bug - bytes are exchanged each time …

### PR DESCRIPTION
**Pull request by mac-michael**
…the function is called on little-endian cpus

### CODE REVIEW

**Comment by rojer** [comment]
ok, i see the issue. but please keep using `d`.

> the function is called on little-endian cpus

that's right, but let's not rely on it.

```
d[0] = new >> 8;
d[1] = new & 0xFF;
```

**Comment by mac-michael** [comment]
> ok, i see the issue. but please keep using `d`.
no problem.

> 
> > the function is called on little-endian cpus
> 
> that's right, but let's not rely on it.
> 
> ```
> d[0] = new >> 8;
> d[1] = new & 0xFF;
> ```
calling mgos_i2c_write_reg_w should be ok on both little and big endian cpus.

```
bool mgos_i2c_write_reg_w(struct mgos_i2c *conn, uint16_t addr, uint8_t reg,
                          uint16_t value) {
  uint8_t tmp[3] = {reg, (uint8_t)(value >> 8), (uint8_t) value};
  return mgos_i2c_write(conn, addr, tmp, sizeof(tmp), true /* stop */);
}
```

btw: mgos_i2c_write_reg_w uses stack variables and mgos_i2c_write_reg_n uses calloc. Which one should be preferred in such situations? Thanks in advance.

**Comment by rojer** [comment]
> calling mgos_i2c_write_reg_w should be ok on both little and big endian cpus.
ah, yes, you're right.

> btw: mgos_i2c_write_reg_w uses stack variables and mgos_i2c_write_reg_n uses calloc. Which one should be preferred in such situations? Thanks in advance.

calloc is used because we don't know upfront how much data is being written and sometimes stack is tight.
though i agree it's probably not much and we could have an optimization for small writes, like 64 bytes or less, use stack.
it's certainly overly inefficient to do 2 byte allocations, like what happens in case of write_w.
if you feel like it, you can do it in a separate PR.

**Comment by mac-michael** [comment]
> 
> > btw: mgos_i2c_write_reg_w uses stack variables and mgos_i2c_write_reg_n uses calloc. Which one should be preferred in such situations? Thanks in advance.
> 
> calloc is used because we don't know upfront how much data is being written and sometimes stack is tight.
> though i agree it's probably not much and we could have an optimization for small writes, like 64 bytes or less, use stack.

True. Thank you.

> it's certainly overly inefficient to do 2 byte allocations, like what happens in case of write_w.

but both mgos_i2c_write_reg_b and mgos_i2c_write_reg_w use stack 
```
bool mgos_i2c_write_reg_w(struct mgos_i2c *conn, uint16_t addr, uint8_t reg,
                          uint16_t value) {
  uint8_t tmp[3] = {reg, (uint8_t)(value >> 8), (uint8_t) value};
  return mgos_i2c_write(conn, addr, tmp, sizeof(tmp), true /* stop */);
}
```
> if you feel like it, you can do it in a separate PR.

What function signatures do you have in mind?
Hmm, or are you talking about mgos_i2c_write_reg_n optimization for low n?

**Comment by rojer** [comment]
i was referring to mgos_i2c_write_reg_n actually, yes.

**Pull request merged**
